### ISSUE TITLE
Some priorities

### ISSUE THREAD

**Issue by ypriverol** [qinchunyuan/FADLEAMSE#9]
@qinchunyuan @mingze: 

1. Here some priorities for the project, in table 4 of the manuscript we have a benchmark using different numbers of spectra starting from 10'000 to 80'000. I recommended to analyze all the data and start the comparison with 100'000 to 4M spectra. 

2. For the similarity benchmark, you use the Java implementation from Lennart teams, https://github.com/compomics/spectrum_similarity; it would be great if you test a C++ implementation that is closer to the python - C++ implementation by GLEAMS. I can try to check with OpenMS guys if they have an implementation. 

3. These guys https://github.com/COL-IU/msCRUSH use the Hash to encode the spectra previous to search, it would be probably interesting to test against them.  

4. You never explored how the PRIDE cluster to train the data to affect the results. One idea is to use for example different reference 500 spectra depending on the instrument. This can improve a lot of the results. I will say the following: 

 - instead of taking the 500 randomly from high-quality clusters. Select the best clusters from different experiments like: 

 - 500 reference spectra from Orbitrap 
 - 500 reference spectra for QTOF
 ... 
Then when you build the model use the different references. This will give you a lot of power to your algorithm because it uses PRIDE cluster - (disseminated data). You can have a model for each Instrument type + species.

**Comment by baimingze** [comment]
@ypriverol 


Good ideas.  

I have discussed these ideas with students, who are going to do the tests respectively.
